<a href="https://colab.research.google.com/github/proshenjitbarua06-dot/skill-morph/blob/main/class_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Given array
arr = np.random.randint(1, 101, 20)

# 1. Print sum, min, and max
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))

# 2. Create a second array and multiply element-wise
arr2 = np.random.randint(1, 101, 20)
result = arr * arr2

print("Second Array:", arr2)
print("Element-wise Multiplication:", result)

Array: [85 33 55 94 56 54 37 55 84 16 84 42 97 44 68 57 70 18  4 10]
Sum: 1063
Min: 4
Max: 97
Second Array: [ 13  88   7  37   2  68  92  85  88 100  56  95  40  39  34  75  82  70
   8  21]
Element-wise Multiplication: [1105 2904  385 3478  112 3672 3404 4675 7392 1600 4704 3990 3880 1716
 2312 4275 5740 1260   32  210]

2 no assaingment

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Dataset/fertility_health_dataset.csv')
print('loaded',df.shape)
df.info()

loaded (2000, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Couple_ID             2000 non-null   object
 1   Female_Age            2000 non-null   int64
 2   Male_Age              2000 non-null   int64
 3   Female_BMI            2000 non-null   float64
 4   Male_BMI              2000 non-null   float64
 5   PCOS                  2000 non-null   object
 6   Period_Regularity     2000 non-null   object
 7   Stress_Level          2000 non-null   float64
 8   Sleep_Quality         2000 non-null   float64
 9   Past_Pregnancies      2000 non-null   int64
 10  Sperm_Count_M_per_mL  2000 non-null   float64
 11  Sperm_Motility_Pct    2000 non-null   float64
 12  Female_Smokes         2000 non-null   object
 13  Male_Smokes           2000 non-null   object
 14  Female_Alcohol        2000 non-null   object
 15  Male_Alcohol          2000 non-null   object
 16  Female_Exercise       2000 non-null   object
 17  Male_Exercise         2000 non-null   object
 18  Pregnancy_Success     2000 non-null   object
dtypes: float64(6), int64(3), object(10)
memory usage: 297.0+ KB

In [5]:
df.head()

,Couple_ID,Female_Age,Male_Age,Female_BMI,Male_BMI,PCOS,Period_Regularity,Stress_Level,Sleep_Quality,Past_Pregnancies,Sperm_Count_M_per_mL,Sperm_Motility_Pct,Female_Smokes,Male_Smokes,Female_Alcohol,Male_Alcohol,Female_Exercise,Male_Exercise,Pregnancy_Success
0,CPL0001,26,28,21.1,30.1,No,Regular,5.4,6.1,1,21.6,81.0,No,Yes,Moderate,No_Alcohol,Light,No_Exercise,Failure
1,CPL0002,39,43,24.1,24.6,No,Regular,2.1,5.6,0,41.5,56.8,No,No,Low,High,Light,Active,Failure
2,CPL0003,34,41,25.4,25.9,Yes,Irregular,5.8,5.1,3,64.5,50.8,No,No,No_Alcohol,No_Alcohol,Light,No_Exercise,Success
3,CPL0004,30,33,28.7,30.1,No,Regular,7.2,4.9,2,80.2,46.6,No,No,Moderate,No_Alcohol,No_Exercise,Active,Success
4,CPL0005,27,31,25.1,22.7,Yes,Irregular,6.3,5.3,3,97.2,53.1,No,Yes,Low,Low,Active,Moderate,Failure

In [6]:
df.tail()

,Couple_ID,Female_Age,Male_Age,Female_BMI,Male_BMI,PCOS,Period_Regularity,Stress_Level,Sleep_Quality,Past_Pregnancies,Sperm_Count_M_per_mL,Sperm_Motility_Pct,Female_Smokes,Male_Smokes,Female_Alcohol,Male_Alcohol,Female_Exercise,Male_Exercise,Pregnancy_Success
1995,CPL1996,34,36,20.8,25.9,Yes,Irregular,5.0,6.6,0,61.2,67.1,No,No,Low,No_Alcohol,Moderate,Moderate,Failure
1996,CPL1997,33,40,24.9,17.0,Yes,Irregular,1.8,5.4,0,52.9,39.8,No,No,Low,No_Alcohol,Moderate,Moderate,Failure
1997,CPL1998,37,42,18.7,25.1,Yes,Irregular,6.3,6.7,2,17.6,65.2,No,No,Low,No_Alcohol,Light,Moderate,Failure
1998,CPL1999,39,40,21.4,21.9,No,Regular,8.3,5.7,1,38.3,55.4,No,No,No_Alcohol,Low,Active,Light,Success
1999,CPL2000,26,30,17.3,27.5,No,Regular,3.1,8.3,1,33.1,66.2,No,Yes,Low,Moderate,No_Exercise,No_Exercise,Failure

In [7]:
df.isnull().sum()

Couple_ID               0
Female_Age              0
Male_Age                0
Female_BMI              0
Male_BMI                0
PCOS                    0
Period_Regularity       0
Stress_Level            0
Sleep_Quality           0
Past_Pregnancies        0
Sperm_Count_M_per_mL    0
Sperm_Motility_Pct      0
Female_Smokes           0
Male_Smokes             0
Female_Alcohol          0
Male_Alcohol            0
Female_Exercise         0
Male_Exercise           0
Pregnancy_Success       0
dtype: int64